# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ACAguas
                                 A QGIS plugin
 Plugin para el manejo de las aguas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-11-10
        copyright            : (C) 2019 by Aguas de Corrientes
        email                : cristain297@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ACAguas class from file ACAguas.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ac_aguas import ACAguas
    return ACAguas(iface)
